### ISSUE TITLE
glimmer-gtk ?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#10]
Hey there Andy,

I noticed you wrote quite a lot of glimmer-libui related code.

glimmer right now shows this as overview for supportable DSLs (or DSL-like components):

    glimmer-dsl-swt
    glimmer-dsl-opal
    glimmer-dsl-xml
    glimmer-dsl-css
    glimmer-dsl-tk
    glimmer-dsl-libui

May I suggest ruby-gtk3 as well? I don't mean to support all of gtk
but a subset, e. g. about the same that libui supports (which uses
gtk on linux too unless I am mistaken).

So for example ...

    Gtk::Window
    Gtk::Button
    Gtk::Entry
    Gtk::Box (:horizontal and :vertical)

and a few more elements. Of course you could go fancy and add CSS as-is,
and like combine it via glimmer-css, but time is limited, so I think adding just
basic support for gtk via glimmer may be nice to have.

There are many more things glimmer could support, such as gosu - there
are a few GUI-elements in gosu, but I don't quite suggest it since it requires
more work. :D  ruby-gtk3 however had works quite nice, and this could just
be for the basic gtk-support. (Sadly I was not able to get it to work on 
windows yet, but ruby-gtk3 works on linux very well.)

Anyway this is just a suggestion, please feel free to close this at any moment
in time. Thanks for reading!

**Comment by AndyObtiva** [comment]
Thank you for the suggestion. 

By the way, [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) already relies on GTK in Linux and I believe [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) relies on GTK for Linux too.

Still, it seems that GTK has very big fans who want to build Linux-only GUI in CRuby, and given that SWT runs on JRuby and LibUI is very minimal in its features, there would be value in supporting GTK directly with Glimmer.

I added Glimmer DSL for GTK to [TODO.md](https://github.com/AndyObtiva/glimmer/blob/master/TODO.md)

I will close this issue once I've made a first gem release of it (e.g. 0.0.1) after I've completed work on [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk).

One question I have for you: do you think it is OK to skip GTK2/GTK3 and immediately support the [new GTK4](https://blog.gtk.org/2020/12/16/gtk-4-0/) with Glimmer DSL for GTK? It seems GTK2 and GTK3 already have a lot of helpful gems in Ruby (like your gem [gtk_paradise](https://rubygems.org/gems/gtk_paradise) if I'm not wrong about you being its author), but GTK4 could benefit most from a Glimmer DSL since it is new and as of today does not have any supporting Ruby gems yet.

**Comment by AndyObtiva** [comment]
0.0.1 is implemented and released: https://rubygems.org/gems/glimmer-dsl-gtk

Here is the project page:
https://github.com/AndyObtiva/glimmer-dsl-swt

I focused on supporting what you mentioned:
- Gtk::Window
- Gtk::Button
- Gtk::Entry
- Gtk::Box (:horizontal and :vertical)

But, also due to Glimmer's dynamic nature, it supports all GTK widgets, properties, and signals that conform to the general GTK conventions.

Thank you again for suggesting this and cheers!

p.s. I built it with gtk3 at the moment because the Ruby gtk4 gem currently has issues. Once gtk4 issues are sorted out, I will switch to supporting it instead.
