### ISSUE TITLE
Glimmer FAQ? (Low priority)

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#12]
Hello Andy,

First, let me preface that glimmer rocks, and the documentation + screenshots you provide are really great.

I have been quickly able to use glimmer-dsl-libui. (I encountered an indirect issue, but this was not related
to glimmer-dsl-libui; I think resizing is somehow slow-ish? Not sure if this is due to my own custom code or
anything else. May be just my impression but libui widgets in the main examples/ provided by kojix2 seem
to be slower than before, but again, there is a high chance I am wrong. I did not test it consistently. Originally
I thought the images were too large, but I noticed this resizing "problem" with kojix2' recent release too,
so I wonder whether something is messed up on my system. I don't recall resizing to be slowish, so it's
confusing me. I wish I would have documented this some months ago, so that I could remember whether
resizing used to be slow in the past ... perhaps I should test it with the earliest libui releases, but this is
a side point, not related to the issue here or necessarily with glimmer or glimmer-dsl-libui.)

Many standalone examples exist - I copy/pasted and then adjusted from that. :D

However had, I also have been wondering whether a FAQ may be useful for the whole glimmer dsl suite.

I don't know how easy it is to do the "write once, work everywhere" philosophy. Would be kind of neat
if we could transition between ruby-gtk, ruby-libui, ruby-tk, ruby-opal (or whatever the name was, I forgot
it right now).

So may a FAQ be useful? I don't mean a FAQ in the sense of Andy maintaining it only. It could be just
a wiki and we can work from there perhaps.

I also don't mean a FAQ to include ALL details, mind you. The main documentation is already useful for
this. But things that may be useful to know, hints, tricks, tipps ... a bit like how StackOverflow works. And
kind of have this as part of glimmer as-is.

I give you an example. Say that a newcomer asks:

"I want a button that pops up a Hello world! widget in glimmer. I would like to see how this works
in the simplest, shortest way for all across glimmer e. g. tk, libui and so forth."

(This is not an ideal example because there are already screenshots covering this, but I am thinking
along those lines, e. g common tasks that users may want to have, and just keep a short-ish FAQ
without too many explanations. The examples as-is that you provide are already quite detailed
and info-rich, so I am not asking to duplicate that effort. Just something that can be quickly 
scanned by newcomers to find interesting things and so.)

Perhaps the github wiki can serve as starting point for that, but I have to admit that I don't like
the github wiki that much - I know from GoboLinux that the wiki there tends to die quite quickly.
But anyway, this is mostly details; the bigger issue or question is whether some kind of FAQ
or FAQ-like entry point (similar to StackOverflow) may be useful for glimmer as a whole in the
long run. Perhaps if there are only few users it's not so relevant, but in the event more people
transition to glimmer then this may be useful. Please feel free to close / disregard. It's mostly
more a sort of question or suggestions; how useful this may be I don't know myself either. 
The examples and screenshots already cover a lot, so people only have to read through them,
which is fine. I am more like thinking of a FAQ as some kind of additional quick-overview
pointer, a bit like zenspider's quickref to ruby (see here: https://www.zenspider.com/ruby/quickref.html
to kind of contain what is useful for many to see quickly, without drowning in details)

**Comment by AndyObtiva** [comment]
You can already submit a Pull Request to add anything to the Glimmer docs if it is missing. 

About the slowdown you mentioned, I already provided workarounds for it over here (shrink image to 24x24):
https://github.com/AndyObtiva/glimmer-dsl-libui/issues/6

Glimmer DSL for LibUI has no slowdown in resizing window otherwise (other than when embedding larger images).

Otherwise, you know my stance on inter-toolkit DSL compatibility. I believe there is value in converting from desktop to web, but not between desktop toolkits. I intentionally have slightly different conventions for each desktop GUI DSL to appeal to each library's audience (e.g. SWT users have their own conventions that typically pass style argument upon widget creation whereas LibUI controls do not take styles but initial values in arguments). I currently see no value in providing adapters between desktop toolkits, but I would see value in enhancing Glimmer DSL for Opal to also adapt Glimmer DSL for LibUI and Tk syntax in addition to already supporting SWT syntax.

Thank you for your feedback.
