### ISSUE TITLE
[Discussion / Suggestion] Would or could GraalVM + native-image be considered as a useful distribution option for glimmer-related applications?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#15]
Hey there Andy,

This is a bit long, so for the "Too long, did not read" summary associated with this issue request - more a
discussion or question -  please see the last line of this issue request. You can easily skip what is "in
between" I think; I tend to write too much. :)

This is more a discussion/question/suggestion. You most likely know about GraalVM and probably already used it
considering you must know java fairly well (see glimmer-dsl-swt for instance and the associated applications
and the associated GUIs, which I assume require some or considerable knowledge of java already as-is).

I remember perhaps two months ago or so the discussions between you and kojix2 in regards to libui + orca and
distributing applications in general. Libui makes this quite useful on windows too - at the least I could get GUIs
to work on windows "out of the box" just fine. Hopefully some hero-dev can keep on maintaining the upstream
libui in the event that andlabs does not have the time / resources to do so, but I digress.

A few weeks ago or so I used native-image from GraalVM for the first time and built a standalone binary which could
be size reduced to about 4 MB or so (in total size; there is some external tool like uxp or something like that
that can reduce the size to that). While that is still quite large, ultimately I don't really care so much
about the overall size as long as things work, and it actually seems faster than what I use on windows, e. g.
"java HelloWorld" takes longer than the native-image produced via GraalVM. And that's quite neat, feels
almost as fast as a compiled .exe from C, on windows. (On Linux things are quite fast, in my experience -
on windows I always struggle when copy-operations are done. Copying from my external USB HDD takes
sooooo much longer on windows than it does on linux ... :( )

The polyglot functionality in GraalVM is also quite interesting - one idea I had was to combine youtube-dl with
some ruby-GUI or  something like that. And there are blog entries of people that got swing to work with
GraalVM (I failed to reproduce this, but it is said that swing support will work eventually via GraalVM;
javafx works already as far as I am aware so that may also be an option; and the polyglot "polylanguage"
approach should allow people to combine quite a bit, yes? A bit like jruby tapping into .rb files).

Have you considered looking at GraalVM + native-image? Would be quite neat if the glimmer-suite may
eventually support that combination, if possible. Perhaps this is too much work right now considering that
GraalVM is changing a lot, but who knows, perhaps in a year or two it would be interesting to see whether
this could be an option. I am still a java noob, though, but I wanted to mention it in the event that this 
was not yet considered for glimmer - or, in the event that it was considered, some obstacles may exist
that make it not as easy. I haven't yet used the Glimmer DSL for SWT but I keep reading updates,
e. g. the perfect-shape gem and custom shapes you recently extended. On that note, by the way, it
would be interesting if these shames could be shown on each variant e. g. tk, gtk, libui, swt, if only
to compare it. Not so much the draggable functionality per se, but simply how to render these shapes
in the different toolkits - but this is a secondary comment, since your available time is not infinite. The
primary TL; DR is:

- Has GraalVM + native-image been considered as a viable, additional "distributable" strategy for
the glimmer suite?

**Comment by rubyFeedback** [comment]
I forgot one use case rationale. This can be explained by e. g. people writing in the glimmer DSL,
and everything works fine on, say, linux - but now they want to get this to work on windows and
OSX too, so having java available (or just the native-image produced file) would be a useful
additional option, if I understood things correctly so far. I don't know how difficult it is to get e. g.
glimmer-dsl-swt to work - I have not yet tested it, but it's now on my todo list. Then I can test the
custom shapes too. :D

(This, by the way, reminds me of gtk + cairo too. At the least we can draw that way. I found the
API of cairo a bit cumbersome, so perhaps the perfect-shape gem simplifies that.)

**Comment by AndyObtiva** [comment]
"Perhaps this is too much work right now considering that GraalVM is changing a lot"

You hit the nail on the head with that statement. I don't trust GraalVM at this time. Also, the standard Java Virtual Machine already supports polyglot software engineering with many languages, like Kotlin and JRuby. In the future, perhaps JRuby itself will offer AOT (Ahead-Of Time) executable compilation since it has been mentioned several times in presentations given by its creators, but until that time, [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) already [supports building native installers](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_PACKAGING_AND_DISTRIBUTION.md) for Windows (MSI & EXE), Mac (DMG, PKG, and APP), and Linux (RPM & DEB) via the JVM-included `jpackage`, automated by the [`glimmer package` command](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_COMMAND.md#packaging). (You can learn more here: https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_PACKAGING_AND_DISTRIBUTION.md)

Of course, JRuby startup time is a bit slow (even with the native executable packaging as EXE on Windows and APP on Mac), so [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt)'s forte is actually building highly sophisticated business applications that get started by company clerks once at the beginning of the day, and are kept on all day long. App startup time does not matter much in that case, but application development productivity matters a lot to businesses, and thus [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt)'s highly thorough and sophisticated features come in very handy in that case.

For applications that should start quickly, [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) is the most promising option at this point. Of course, as you mentioned, it has no automated methods for producing app executables on Mac and Linux yet though OCRA could be used on Windows as you already mentioned.

Regarding the [`perfect-shape` gem](https://github.com/AndyObtiva/perfect-shape), one thing to clarify is that it is a Math Geometric Algorithm library, not a GUI shape drawing toolkit. In other words, it is used in order to make calculations such as "is the mouse click point inside a shape or composite shape?", "does this shape intersect the screen viewport rectangle?", etc... So, [Perfect Shape](https://github.com/AndyObtiva/perfect-shape) is an auxiliary library that helps with adding advanced features to GUI toolkits, such as effortless declarative Drag & Drop. I already do that in [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) because Java already implements these algorithms. Ruby on the other hand does not have an equivalent or a complete geometry library that covers all GUI cases with a uniform API, so this is where [Perfect Shape](https://github.com/AndyObtiva/perfect-shape) helps. That way, I could use it to augment [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) with the same advanced Drag & Drop features that [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) has. I am not there yet as I still need to finish all planned features for version 1.0 of [Perfect Shape](https://github.com/AndyObtiva/perfect-shape) before I get to that point. But, that is my plan behind it. It is to add advanced Drag & Drop to [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui).

Otherwise, both [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) and [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) already have complete shape drawing facilities. [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) does so via the [Canvas Shape DSL](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_GUI_DSL_SYNTAX.md#canvas-shape-dsl), and [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) does so via the [Area API](https://github.com/AndyObtiva/glimmer-dsl-libui#area-api).

Anyways, until I think that GraalVM is a reliable option, I am dismissing for the time being (closing this issue). I would much rather JRuby supported AOT compilation itself since it is already a very reliable language runtime used by thousands of businesses (not just an experiment).

**Comment by AndyObtiva** [comment]
I changed my mind about GraalVM Native Image. I would like to give it a try in case it offers anything of use to Glimmer DSL for SWT (even if it already supports native executable packaging).

I am reopening this issue until I have expanded some effort into trying GraalVM Native Image out. 

Thank you for reporting.

**Comment by AndyObtiva** [comment]
According to the research I just did, TruffleRuby is not compatible with JRuby. Worse yet, its Graal Native Image does not really do AOT (ahead-of-time) compilation to the Ruby code itself, yet only to the Graal+Truffle implementation code:
https://github.com/oracle/truffleruby/blob/67ee8b015d729749591ceff8b77037eb606bf3df/doc/contributor/native-image.md

As such, my initial gut feeling was right for avoiding TruffleRuby, and I do not see value in supporting it for the time being, especially given that Glimmer DSL for SWT [already supports native executable packaging](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_PACKAGING_AND_DISTRIBUTION.md) on Mac, Windows, and Linux.
