### ISSUE TITLE
[Idea] A simplified DSL variant for "common people"

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#16]
Hey there Andy,

This is more an idea, so please feel free to close it.

I was about to suggest a larger "issue" for the whole glimmer suite/DSL,
but I think it is better to perhaps split up my ideas, and just isolate one
component. So that explains why I opened this "issue", more an idea,
for just one thing really.

Glimmer aims to use an expressive DSL. For instance, to re-use your
examples from glimmer-dsl-gtk, a rectangle or an arc can be defined
 like:

    rectangle(0, 0, 256, 256) {
     # more stuff here
    }

    # radial pattern
    arc(128.0, 128.0, 76.8, 0, 2 * Math::PI) {
     # more code there
    }

This is ok, but I was wondering ... what if we could use a "pseudo"-DSL
that normal people could use? Something like a DSL on top of the
glimmer-DSL. A meta-meta-glimmer. :D

I don't have an example of how I would envision that (coming up with 
good, simple syntax is hard), but something that even elderly people could
use easily, and perhaps even not just text only (though a simplified text-DSL
would be nice), but something like ... glade for gtk using XML.

Now, I am NOT suggesting to use XML as such, but here I refer more to
the GUI-building part that people can use via glade. Something like a 
meta-builder for glimmer. In glimmer. :D

I kind of  imagine that as a big win if elderly people could re-assemble 
the "desktop" or application they'd want to have. (I refer to elderly 
people who may not be in perfect health, but are still able to 
learn. With dementia it is a bit harder, so I more refer to people who
may not have been programmers, but are mentally still in a good 
state - something to simplify making GUIs.)

Anyway, this is part of a larger idea I had - something like a unified "pipe"
system with object-orientation in mind, but based on widget-usage. Where
you kind of model your applications around different widgets that could
be re-used. And different people could write them, and then just "plug
in new functionality", like an ecosystem of widgets. I dream of a world
with unrestricted wigets! :D

It's a bit hard to describe, and I don't want to distract from the singular
idea here (a simplified DSL, or a meta-builder GUI for creating glimmer
applications, in glimmer), but a bit what the ring programming language
aims to do: https://ring-lang.github.io/

And perhaps also your other project, e. g. that editor you have 
https://github.com/AndyObtiva/glimmer-dsl-swt or the table that a
user can modify. My idea is mostly based on the "how should a 
GUI toolset look if it tries to target average people in general"
(so not just the elderly; common people who may not be 
programmers, if you understand what I mean).

Anyway, I end this here - perhaps I will file a longer meta-meta-meta
issue for the glimmer DSL, but I feel that it already deducts from your
time so ... I am not going to create too many issues. Or trying not to. :D

**Comment by AndyObtiva** [comment]
First of all, create as many issues as you want. I don't mind. In fact, I appreciate it. It encourages me to implement features and fix issues faster.

> Glimmer aims to use an expressive DSL. For instance, to re-use your
> examples from glimmer-dsl-gtk, a rectangle or an arc can be defined
> like:
> 
> ```ruby
> rectangle(0, 0, 256, 256) {
>  # more stuff here
> }
> 
> # radial pattern
> arc(128.0, 128.0, 76.8, 0, 2 * Math::PI) {
>  # more code there
> }
> ```
> 
> This is ok, but I was wondering ... what if we could use a "pseudo"-DSL
> that normal people could use? Something like a DSL on top of the
> glimmer-DSL. A meta-meta-glimmer. :D

To answer your question, check out the [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) equivalent of GTK's cairo syntax (called [Canvas Shape DSL](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_GUI_DSL_SYNTAX.md#canvas-shape-dsl)):

```ruby
require 'glimmer-dsl-swt'

include Glimmer

shell {
  text 'Canvas Shape DSL'
  minimum_size 200, 220
  
  canvas {
    background :white
    
    rectangle(30, 50, 140, 100, 40, 80) {
      background :yellow
    }
    
    rectangle(30, 50, 140, 100, 40, 80) {
      foreground :red
      line_width 3
    }
  }
}.open
```

![rounded rectangle](https://github.com/AndyObtiva/glimmer-dsl-swt/raw/master/images/glimmer-canvas-shape-dsl-rectangle-round-angles.png)

Glimmer DSL for SWT also supports a more verbose syntax that is more readable to people not familiar with the default [Canvas Shape DSL](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_GUI_DSL_SYNTAX.md#canvas-shape-dsl) (the SWT equivalent of Cairo) syntax:
```ruby
require 'glimmer-dsl-swt'

include Glimmer

shell {
  text 'Canvas Shape DSL'
  minimum_size 200, 220
  
  canvas {
    background :white
    
    rectangle {
      x 30
      y 50
      width 140
      height 100
      arc_width 40
      arc_height 80
      background :yellow
    }
    
    rectangle {
      x 30
      y 50
      width 140
      height 100
      arc_width 40
      arc_height 80
      foreground :red
      line_width 3
    }
  }
}.open
```

![rounded rectangle](https://github.com/AndyObtiva/glimmer-dsl-swt/raw/master/images/glimmer-canvas-shape-dsl-rectangle-round-angles.png)

Notice how all the shape properties are verbosely and clearly stated?! This can be helpful to people new to that [Canvas Shape DSL](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_GUI_DSL_SYNTAX.md#canvas-shape-dsl), but once they master it, they might prefer to use the shorter original syntax above instead.

This same exactly solution can be transferred to [Glimmer DSL for GTK](https://github.com/AndyObtiva/glimmer-dsl-gtk) in the future (and all other Glimmer DSLs eventually). Just please be patient since it is still very new and only alpha software at this point. If you want this alternative syntax solution to be developed faster, you can open an issue request about it in [Glimmer DSL for GTK](https://github.com/AndyObtiva/glimmer-dsl-gtk)!

> I kind of imagine that as a big win if elderly people could re-assemble
> the "desktop" or application they'd want to have. (I refer to elderly
> people who may not be in perfect health, but are still able to
> learn. With dementia it is a bit harder, so I more refer to people who
> may not have been programmers, but are mentally still in a good
> state - something to simplify making GUIs.)

I disagree. The elderly you seem to be targeting are computer users, but not software engineers. Do not mix the two categories together. Users are not programmers! Attempting to provide them with software engineering tools will only confuse them! Instead, if you want to serve them in the best way possible, build GUI applications for them instead that accomplish their user goals (not programming goals).  So, if someone is using the computer to communicate with their nephews online, give them an online chat desktop application for example, not code or software engineering tools. That is how you serve them best!

> Anyway, this is part of a larger idea I had - something like a unified "pipe"
> system with object-orientation in mind, but based on widget-usage. Where
> you kind of model your applications around different widgets that could
> be re-used. And different people could write them, and then just "plug
> in new functionality", like an ecosystem of widgets. I dream of a world
> with unrestricted wigets! :D

We already have that! It's called Ruby gems! In fact, Glimmer DSL for SWT makes extensive use of it. Check out all of those widget gems for Glimmer DSL for SWT (one day I dream Glimmer DSL for LibUI will have the same):
- https://github.com/AndyObtiva/glimmer-cw-nebula
- https://github.com/AndyObtiva/glimmer-cw-video
- https://github.com/AndyObtiva/glimmer-cw-cdatetime-nebula
- https://github.com/AndyObtiva/glimmer-cw-browser-chromium
- https://github.com/AndyObtiva/glimmer-cp-cylinder
- https://github.com/AndyObtiva/glimmer-cp-cube
- https://github.com/AndyObtiva/glimmer-cp-stickfigure
- https://github.com/AndyObtiva/glimmer-cp-bevel
- https://github.com/AndyObtiva/glimmer-cp-messageboxpanel

I would imagine that any of these custom widgets can support multiple GUI toolkits if needed (or perhaps namespace them like glimmer-libui-cw-video and glimmer-gtk-cw-video for example). cw stands for Custom Widget. cp stands for Custom shaPe.

> It's a bit hard to describe, and I don't want to distract from the singular
> idea here (a simplified DSL, or a meta-builder GUI for creating glimmer
> applications, in glimmer), but a bit what the ring programming language
> aims to do: https://ring-lang.github.io/

Ring strikes me as nothing but a mish-mash of both Ruby and Python, so there is nothing new there to be inspired by. It's got nothing on Ruby. Ruby came up with all the ideas you might see in Ring long time ago. Also, since Ring is empty space dependent like Python, it is actually considered unsafe even to software engineers to use since mistakes in empty space could cause applications to break. That's why I avoid Python, and the last thing I want is another language like Python. No thanks, I got Ruby, which is inspired by the good parts of Python only, but also adds the good parts of Perl, Smalltalk, Basic, and Lisp. That's much better and is still innovative enough to the point that no other dynamic language competes with Ruby today.

> Anyway, I end this here - perhaps I will file a longer meta-meta-meta
> issue for the glimmer DSL, but I feel that it already deducts from your
> time so ... I am not going to create too many issues. Or trying not to. :D

File as many issues as you like. Don't worry about my time. It is always good to record ideas before they are forgotten in order to work on them at a later time in the future even if we are occupied today.

I believe I addressed your concerns sufficiently to warrant closing this issue. 

Thanks and keep the feedback coming!
