### ISSUE TITLE
Glimmer gosu support? (This is more a question though)

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#26]
This is more a short question, sorry for that.

Do you think glimmer may support gosu one day? And could this then also work
on windows?

Gosu does not have a lot of support for custom widgets, naturally, since it caters
more towards games. But I wondered since you can create nice games in gosu,
so useful widgets could also be supported. But it probably would require quite a 
lot of time and your time is limited, so don't worry too much about that question.
I am more interested in how feasible it may be. "Write once, glimmer-run everywhere"
slogan. (Actually my primary use case for windows comes from elderly relatives
who depend on Windows.)

**Comment by AndyObtiva** [comment]
You can accomplish your Windows goals already in any of the existing [Glimmer](https://github.com/AndyObtiva/glimmer) toolkits. As such, I don't see value in supporting a new toolkit for your Windows needs. It would just be a big waste of time. Learn one of the existing toolkits well instead and you'll have your Windows app ready in no time.

I already gave you an implementation in [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) in this issue report:
https://github.com/AndyObtiva/glimmer-dsl-libui/issues/31

Also, if you don't like it, then you can try to build in [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt), which is the richest Glimmer DSL in features. As I've mentioned to you before, it can [package Windows EXE/MSI files](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_PACKAGING_AND_DISTRIBUTION.md), so your user can install as a native application on Windows (without needing to have Java or JRuby) and use just like any other Windows application. If you're stuck somehow with Glimmer DSL for SWT, hit me up in an issue or in [Gitter Chat](https://gitter.im/AndyObtiva/glimmer). I'd be happy to help. I could even implement the main screen or skeleton of the app if you like. Glimmer is so produtive, it takes almost no time, so I don't mind at all.

Otherwise, since you have been having trouble with installing GTK on Windows, I probably would recommend [Glimmer DSL for FX](https://github.com/AndyObtiva/glimmer-dsl-fx) next since it is rich in features and includes Windows binaries out of the box (just like LibUI), so you can just install your app gem in Windows, and it would work (just like LibUI). Unfortunately, FXRuby does not have a native Windows look and feel (unlike LibUI and SWT), but it might be good enough for your user anyways. If you need help with this toolkit, hit me up about it in an issue or in [Gitter Chat](https://gitter.im/AndyObtiva/glimmer). That toolkit is still brand new, so it is missing many features, but it might work well as is for your needs anyways.

Tcl/Tk is another option that is rich in features, but its setup is complicated, so I would probably avoid unless all other options became unfeasible.

In any case, I am closing this issue as I don't see as useful.
