### ISSUE TITLE
[Idea, please close as desired] Glimte-Glimmer for Everyone \o/ (GUIs everywhere)

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#35]
I am stalking you as you may know :)

And I found Glimte indirectly due to your fork.

https://github.com/Phaengris/Glimte

I also found nebula that way (did not know it exists prior to your changelog entry at github).

https://www.eclipse.org/nebula/

What if we'd have this (that is, both combined) for all of glimmer? Kind of like the desire/goal to be able to have as
many widgets as possible, but without necessarily the user having to write them for any specific toolkit? A bit like
LEGO building blocks. We assemble and re-use the blocks to create stuff. Larger stuff. We build complexity. From
small to big.

We could then write the logic once, and glimmer would do the rest for us. So people could then
use any GUI toolkit they'd like to, such as via a commandline flag to switch. And, ideally, if that
were possible, to also have rails/sinatra/javascript code for the www. Like, we write a game
in glimmer, like tic tac toe (just as a silly example) but we can use it on the www as well even
via a simple plain .html (perhaps opal can help there). 

Or we could use and specify to use the nebula widgets for glimmer, if these work, for java
centric applications.

And, perhaps if it goes super-fancy, to use jruby, and even graalVM for natively compiled
static GUI applications. Not sure if that is easily possible but that would be kind of neat -
write once, run every GUI. :D

Perhaps not even in ruby only or java, but to bridge into C, C++ and other languages.

And not even requiring a user to know ruby, in order to use glimmer. Kind of like an
abstraction layer people could just use as a template or something like that. Where they
focus on content, then add a few checkboxes for the desired style, and glimmer does the
rest for them. A bit like the old Glade XML, but simpler to use.

Anyway. I have no idea if the above makes any sense to you at all. It's a bit semi-random
so apologies for that. I just think it would be interesting to see how far glimmer could
push the boundaries there. In some ways glimmer kind of rescued the old shoes from
_why too, in the sense of writing in a ruby-centric DSL and have it "just work".

**Comment by AndyObtiva** [comment]
I am closing this because the requirements that are mentioned are too broad, too vague, and too expensive to implement. I’d rather solve smaller problems here and there and have that add up into a bigger solution kinda like how I came up with Glimmer to solve my own problems of writing too much difficult to maintain code to use SWT in Java. Let’s continue to solve smaller problems and have that add up to higher solutions instead. And, if the need for what you mentioned comes up in the future, we will tackle that after having many small solutions ready to integrate. 

I am closing this issue.
