### ISSUE TITLE
Glimmer statistics (aka overview)?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#39]
I am trying to improve on opal lately so I stumbled (again I think) over https://github.com/AndyObtiva/glimmer-dsl-opal.

You write it is about 76% complete. You also bring in many examples.

It can be a bit confusing to know which examples / samples work on which glimmer variant. So I was thinking ...
what if we could have full glimmer statistics? That is, to automatically assess which particular subprojects reached
this or that milestone? Say, the glimmer wxruby bindings may be less complete than the SWT parts.

For instance, this could help users answer this question: "does tetris work on glimmer-opal", and so forth.

Not sure if you get what I mean here. Ideally something that you could run programmatically and which then
generates some table or something, for embedding into .md, and/or an image as a quick overview (text is
probably simpler though).

Anyway, as always feel free to proceed in any way shape or form. My use case was specifically to see (and
try) using glimmer + opal to learn from it, ideally via examples that are simple but still useful (these should
make it easier to learn; more complex projects can be a bit daunting).

**Comment by AndyObtiva** [comment]
All the examples that are included in [Glimmer DSL for Opal](https://github.com/AndyObtiva/glimmer-dsl-opal) should work, including Tetris, so I am not sure what your issue is about. Just go through them all, and if any are broken, report them for me to fix.

Otherwise, I do not see a value in listing "stats" like which samples work under which project in one master table. But, if you find that useful, knock yourself out. You can build such a master table, and then contribute in a pull request or just put it in its own GitHub project.

I am closing this issue.
