### ISSUE TITLE
Enable GitHub Discussions on all glimmer repos

### ISSUE THREAD

**Issue by postmodern** [AndyObtiva/glimmer#40]
Please enable GitHub Discussions so users can ask questions that are not necessary bugs or issues. GitHub Discussions would also allow you to post announcements.

**Comment by AndyObtiva** [comment]
You might have missed it in the README, but the reason why discussions are not enabled is because we have a Glimmer Gitter chat. It’s better suited for discussions. 

https://gitter.im/AndyObtiva/glimmer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Feel free to ask me any questions you have over there.
