### ISSUE TITLE
Glimmer support for jruby + SWING?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#42]
Hey there Andy,

Sorry if that was suggested before.

You already support tons of toolkits, SWT, libui and so forth.

Does glimmer support jruby + SWING? The reason I am asking is because
if not then this could be a low-hanging fruit, since swing, even though it
may be outdated, is quite usable. I tested it on windows too, e. g. 
jruby .exe, and it works. So perhaps that could be an additional use case
for glimmer, unless there is some reason why jruby + swing may not be
supported. Either way I just wanted to briefly mentioned it. Please feel
free to close this as you deem it fit.

**Comment by AndyObtiva** [comment]
Yes: https://github.com/AndyObtiva/glimmer-dsl-swing

A quick search of the word "Swing" in the Glimmer README would have found you the answer. Please try the "Find" capability of the browser first next time before asking. It is very clearly stated in the [Glimmer](https://rubygems.org/gems/glimmer) DSL Comparison Table.

That said, I advise anyone using JRuby to build apps with Glimmer DSL for SWT only (unless they have old Swing code they want to reuse). SWT provides native widgets unlike Swing, which doesn't, so SWT provides the correct look on Mac, Windows, and Linux. And, it offers higher performance in general as a result. Only uninformed developers use Swing when SWT is available very conveniently with Glimmer DSL for SWT. Please build something with Glimmer DSL for SWT and ask me questions about that in the future if you want to use JRuby instead of asking about many toolkits without building anything. That would be a lot more useful. I might start closing theoretical questions immediately from you if you don't include code that shows effort in using Glimmer.
