### ISSUE TITLE
[Idea] [Glimmer Videos] Could more be added in the time-range of 1-5 minutes, for a FAQ-style like question-answer+demo, or just a short demo?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#47]
Hey there Andy,

You provide some videos here on youtube: https://www.youtube.com/@glimmer-dsl/videos

The number of views goes from around 20 to 1200. On average probably between 40-70 or so,
give or take. I also assume that because there are not so many unique viewers here, the time
spent on these video may not be worth your time investment, e. g. as opposed to working 
for money or working for fun / hobby. So this probably does not have the highest priority;
improving glimmer itself has probably a much more vital focus from your side.

Nonetheless I was thinking ... what if glimmer would not only have something like a FAQ,
but also a FAQ + videos? I am not saying every FAQ entry needs a video, but perhaps a
few "todo FAQ" entries, e. g. "how can I integrate tetris into this custom ruby-gtk widget"
could be explained by a video (or, more generally, how to integrate tetris into ALL of these,
e. g. ruby-tk, rails and so forth). The idea would be for you to just showcase a few more 
things specifically focusing on problems people MAY have, for instance, what problems
people may have when using glimmer, and normally may ask on StackOverflow instead. Also, for these
folks to have a quick entry point. Or perhaps get ideas from these videos that are more interesting
for their particular use case(s).

The length of these videos should not be too large, say 1-5 minutes or so, give or take.
Possibly between 2-3 minutes may be best; I know that I myself have a very hard time
concentrating for more than 10 minutes. And too short is also not good because it leaves
my brain's memory so quickly, hence why I think 2-3, or a bit more, may be ideal.

Something that is also managable and fun for you without any burn-out, say, 1 video
per month or 10 per year in a FAQ style. (So, in total, that would still probably be less
than a full hour of video per year, so I think that is an acceptable time investment.)

Over time more and more videos could help people who want to either learn glimmer,
or just need a short intro to this or that problem domain, from which they can learn.

If you don't have a specific topic at hand you could also just do a quick review of what
you did in the last 3-12 days or so, related to glimmer. So a bit more like a NEWS entry.
It should not be too long, and it can just cover a few topics you may find interesting,
and a short demo with a tiny bit of explanation.

Anyway, this is just an idea. Please feel free to disregard as is or close at any moment
in time.

**Comment by AndyObtiva** [comment]
Everything you asked for either exists in some form or another (like the Glimmer FAQ, videos, Ruby meetup presentations, and blog posts) or could be done by you as a contribution if you really need. 

I told you several times I’d like contributions from you not requests. You’ve made way too many requests already. This is an open source project. It’s only fair to contribute. 

If you want to know what I did in the last 12 days, just check out my Code Master blog. You already know about it, so I’m not even sure why you asked for that. 

It’s important to keep things as simple as possible and accept things when they’re good enough instead of asking for more all the time. But, if you really really really need more (I highly doubt it), just contribute it. 

I’m closing this request as again it’s disappointing in how it asks for things that do exist. It shows lack of effort. At least submit a PR next time.
